# Generated by Django 5.1.4 on 2025-06-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Myapp", "0011_cashout_motif"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="puchase_price",
        ),
        migrations.AlterField(
            model_name="cashout",
            name="motif",
            field=models.CharField(default="Aucun motif", max_length=30),
        ),
    ]
