# Generated by Django 5.1.4 on 2025-06-05 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Myapp", "0012_remove_product_category_remove_product_price_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
