# Generated by Django 5.1.4 on 2025-06-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Myapp", "0015_deliverynote_deliverynoteitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="bureau",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Myapp.bureau",
            ),
            preserve_default=False,
        ),
    ]
