# Generated by Django 5.1.4 on 2025-06-15 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Myapp", "0016_deliverynote_bureau"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
